# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDFMerger.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDFMergerUI(object):
    def setupUi(self, PDFMergerUI):
        PDFMergerUI.setObjectName("PDFMergerUI")
        PDFMergerUI.setEnabled(True)
        PDFMergerUI.resize(403, 392)
        PDFMergerUI.setWindowTitle("PDFMerger")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon_PDF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PDFMergerUI.setWindowIcon(icon)
        PDFMergerUI.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(PDFMergerUI)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutMain.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.pdf_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.pdf_list.setObjectName("pdf_list")
        self.verticalLayoutMain.addWidget(self.pdf_list)
        self.horizontalLayout_radioButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_radioButtons.setObjectName("horizontalLayout_radioButtons")
        self.radioButton_merge = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_merge.setAutoFillBackground(False)
        self.radioButton_merge.setChecked(True)
        self.radioButton_merge.setObjectName("radioButton_merge")
        self.horizontalLayout_radioButtons.addWidget(self.radioButton_merge)
        self.radioButton_split = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_split.setObjectName("radioButton_split")
        self.horizontalLayout_radioButtons.addWidget(self.radioButton_split)
        self.verticalLayoutMain.addLayout(self.horizontalLayout_radioButtons)
        self.process_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.process_label.setText("")
        self.process_label.setObjectName("process_label")
        self.verticalLayoutMain.addWidget(self.process_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayoutMain.addItem(spacerItem)
        self.action_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.action_button.setObjectName("action_button")
        self.verticalLayoutMain.addWidget(self.action_button)
        self.load_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.load_button.setObjectName("load_button")
        self.verticalLayoutMain.addWidget(self.load_button)
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayoutMain.addWidget(self.save_button)
        self.horizontalLayout_deleteButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_deleteButtons.setObjectName("horizontalLayout_deleteButtons")
        self.delete_all_files_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_all_files_button.setObjectName("delete_all_files_button")
        self.horizontalLayout_deleteButtons.addWidget(self.delete_all_files_button)
        self.delete_selected_file_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_selected_file_button.setObjectName("delete_selected_file_button")
        self.horizontalLayout_deleteButtons.addWidget(self.delete_selected_file_button)
        self.verticalLayoutMain.addLayout(self.horizontalLayout_deleteButtons)
        PDFMergerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PDFMergerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        PDFMergerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PDFMergerUI)
        self.statusbar.setObjectName("statusbar")
        PDFMergerUI.setStatusBar(self.statusbar)
        self.action_ffnen = QtWidgets.QAction(PDFMergerUI)
        self.action_ffnen.setObjectName("action_ffnen")
        self.actionexit = QtWidgets.QAction(PDFMergerUI)
        self.actionexit.setObjectName("actionexit")
        self.actionexit_2 = QtWidgets.QAction(PDFMergerUI)
        self.actionexit_2.setObjectName("actionexit_2")
        self.menuDatei.addAction(self.actionexit_2)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(PDFMergerUI)
        QtCore.QMetaObject.connectSlotsByName(PDFMergerUI)

    def retranslateUi(self, PDFMergerUI):
        _translate = QtCore.QCoreApplication.translate
        self.radioButton_merge.setText(_translate("PDFMergerUI", "Merge"))
        self.radioButton_split.setText(_translate("PDFMergerUI", "Split"))
        self.action_button.setText(_translate("PDFMergerUI", "Merge"))
        self.load_button.setText(_translate("PDFMergerUI", "Load File"))
        self.save_button.setText(_translate("PDFMergerUI", "Save File"))
        self.delete_all_files_button.setText(_translate("PDFMergerUI", "Delete All Files"))
        self.delete_selected_file_button.setText(_translate("PDFMergerUI", "Delete Selected File"))
        self.menuDatei.setTitle(_translate("PDFMergerUI", "Datei"))
        self.action_ffnen.setText(_translate("PDFMergerUI", "öffnen"))
        self.actionexit.setText(_translate("PDFMergerUI", "exit"))
        self.actionexit_2.setText(_translate("PDFMergerUI", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PDFMergerUI = QtWidgets.QMainWindow()
    ui = Ui_PDFMergerUI()
    ui.setupUi(PDFMergerUI)
    PDFMergerUI.show()
    sys.exit(app.exec_())
